<?php

namespace Crisjohn02\Dbimport;

use Crisjohn02\Dbimport\Console\Commands\ExportDb;
use Crisjohn02\Dbimport\Console\Commands\ImportDb;
use Illuminate\Support\ServiceProvider;

class DbImportServiceProvider extends ServiceProvider
{

    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                ImportDb::class,
                ExportDb::class,
            ]);
        }
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}